name: Jest CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: CI=true npm test -- --watchAll=false --coverage

    # - name: Print the Total Coverage
    #     id: coverage-percent
    #     shell: bash
    #     run: |
    #       value=`sed -n 47p coverage/lcov-report/index.html | awk -F '>' '{print $2}' | awk -F '%' '{print $1}'`
    #       echo "::set-output name=coverage::$value"
    #       echo $value

    # # https://github.com/actions/github-script#apply-a-label-to-an-issue
    # - name: Add Coverage Label
    #   uses: actions/github-script@v2
    #   with:
    #     github-token: ${{secrets.GITHUB_TOKEN}}
    #     script: |
    #       github.issues.setLabels({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         labels: ['COV: ${{steps.coverage-percent.outputs.coverage}}']
    #       })